name: rclone_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.1.5
  rclone_client:
    path: ../rclone_client
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/utils/assets/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true

  assets:
    - assets/
