name: rclone_flutter
description: BPlace
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.1.5
  rclone_client:
    path: ../rclone_client
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.6
  flutter_web_plugins:
    sdk: flutter
  equatable: ^2.0.5
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  flutter_native_splash: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test:
    sdk: flutter
  rename_app: ^1.6.1

flutter_gen:
  output: lib/core/utils/assets/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: JacquardaBastarda9
      fonts:
        - asset: fonts/JacquardaBastarda9-Regular.ttf
    - family: Silkscreen
      fonts:
        - asset: fonts/Silkscreen-Regular.ttf

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: assets/bplace_logo.png
  image_web: assets/bplace_logo512.png
  color: "#313338"
  android_12:
    image: assets/bplace_logo.png
    color: "#313338"