version: '3.7'

services:
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rclone
      POSTGRES_PASSWORD: "t-EnPQPUmJ61eDhklL5dKA9a0-NzYfZK"
    volumes:
      - rclone_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "kSyXbV9qyGVSmdbnZ4MAM71_io2h5TF5"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  rclone_data:
