name: Create and publish Server Image

on:
  push:
    branches: ['main']
    paths:
      - 'rclone_server/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'passwords.yaml'
          fileDir: 'rclone_server/config/'
          encodedString: ${{ secrets.PASSWORDS_BASE64 }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: rclone_server/
          push: true
          tags:
            ghcr.io/${{ github.actor }}/rclone_server:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to VPS
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.actor }}/rclone_server:latest
            cd /home/albinson/containers/rclone_server
            docker compose down
            docker compose up -d --build
  